Test if satis-repo output errors in journal

diff --git a/modules/satis/templates/satis-repo.sh.erb b/modules/satis/templates/satis-repo.sh.erb
--- a/modules/satis/templates/satis-repo.sh.erb
+++ b/modules/satis/templates/satis-repo.sh.erb
@@ -1,9 +1,15 @@
 #!/bin/bash +e
 
 satis_ok='yes'
-output_file="/tmp/satis-repo-$3.err"
+satis_service="satis-repo-$3"
+output_file="/tmp/$satis_service.err"
 
-trap "echo '[satis-daemon] satis-$3 failure on <%= @facts['fqdn'] %>, see /tmp/satis-repo-$3.err' > /dev/stderr" ERR EXIT
+catch_error () {
+  time=$(date "+%s")
+  cp ${output_file} ${output_file}.${time}
+  echo "[${satis_service}] failure on <%= @facts['fqdn'] %>, see ${output_file}.${time}" 1>&2
+}
+trap catch_error ERR EXIT
 
 while [ $satis_ok == 'yes' ]; do
   if ! $(/var/lib/satis/satis/bin/satis --no-interaction build $1 $2 >${output_file} 2>&1); then
